let start=datetime('${start}');
let end=datetime('${end}');
let end_resp=datetime_add('minute', 5, end);

let req=${table_name}
| where INSERTED_TIMESTAMP between (start .. end)
| where TIPO_EVENTO !in ("paSendRT", "paSendRTV2")
| where SOTTO_TIPO_EVENTO == "REQ"
| sort by SESSION_ID asc, TIPO_EVENTO asc, INSERTED_TIMESTAMP asc
| serialize
| extend PAIR_SEQ = row_number(1, prev(SESSION_ID) != SESSION_ID or prev(TIPO_EVENTO) != TIPO_EVENTO);

let resp=${table_name}
| where INSERTED_TIMESTAMP between (start .. end_resp)
| where TIPO_EVENTO !in ("paSendRT", "paSendRTV2")
| where SOTTO_TIPO_EVENTO == "RESP"
| sort by SESSION_ID asc, TIPO_EVENTO asc, INSERTED_TIMESTAMP asc
| serialize
| extend PAIR_SEQ = row_number(1, prev(SESSION_ID) != SESSION_ID or prev(TIPO_EVENTO) != TIPO_EVENTO);

req
| join kind=inner resp on SESSION_ID, TIPO_EVENTO, PAIR_SEQ
| extend SOTTO_TIPO_EVENTO="REQ/RESP"
| sort by INSERTED_TIMESTAMP asc
| project INSERTED_TIMESTAMP_REQ=INSERTED_TIMESTAMP, INSERTED_TIMESTAMP_RESP=INSERTED_TIMESTAMP1, IS_EVENT_MULTI_PAYMENT, NAV, PA_EMITTENTE, IUV, CREDITOR_REF_ID, TOKEN, PSP, INTERMEDIARIO_PSP, INTERMEDIARIO_PA, CANALE, STAZIONE, OUTCOME_REQ=OUTCOME, OUTCOME_RESP=OUTCOME1, FAULT_CODE, SESSION_ID, UNIQUE_ID=UNIQUE_ID, EVENT_ID_REQ=UNIQUE_ID, EVENT_ID_RESP=UNIQUE_ID1, TIPO_EVENTO, SOTTO_TIPO_EVENTO, SERVICE_IDENTIFIER, PAYMENT_METHOD
${estimates}

