let start=datetime('${start}');
let end=datetime('${end}');
let end_resp=datetime_add('minute', 5, end);

let req=${table_name}
| where INSERTED_TIMESTAMP between (start .. end)
| where TIPO_EVENTO !in ("paSendRT", "paSendRTV2")
| where SOTTO_TIPO_EVENTO == "REQ";

let resp=${table_name}
| where INSERTED_TIMESTAMP between (start .. end_resp)
| where TIPO_EVENTO !in ("paSendRT", "paSendRTV2")
| where SOTTO_TIPO_EVENTO == "RESP";

req
| join kind=inner resp on SESSION_ID, TIPO_EVENTO
| extend SOTTO_TIPO_EVENTO="REQ/RESP"
| sort by INSERTED_TIMESTAMP asc
| project INSERTED_TIMESTAMP_REQ=INSERTED_TIMESTAMP, INSERTED_TIMESTAMP_RESP=INSERTED_TIMESTAMP1, IS_EVENT_MULTI_PAYMENT, NAV, PA_EMITTENTE, IUV, CREDITOR_REF_ID, TOKEN, PSP, INTERMEDIARIO_PSP, INTERMEDIARIO_PA, CANALE, STAZIONE, OUTCOME_REQ=OUTCOME, OUTCOME_RESP=OUTCOME1, FAULT_CODE, SESSION_ID, UNIQUE_ID=UNIQUE_ID, EVENT_ID_REQ=UNIQUE_ID, EVENT_ID_RESP=UNIQUE_ID1, TIPO_EVENTO, SERVICE_IDENTIFIER, PAYMENT_METHOD
${estimates}

