let start=datetime('${start}');
let end=datetime('${end}');
${table_name}
| where INSERTED_TIMESTAMP between (start .. end)
| where TIPO_EVENTO in ("activatePaymentNotice", "activatePaymentNoticeV2")
| where (
	(isnotempty(trim(" ", tostring(NAV))) and isnotempty(trim(" ", tostring(PA_EMITTENTE))))
	or
	(isempty(trim(" ", tostring(NAV))) and isempty(trim(" ", tostring(PA_EMITTENTE))) and isnotempty(trim(" ", tostring(TOKEN))))
)
| sort by INSERTED_TIMESTAMP asc
| project INSERTED_TIMESTAMP, IS_EVENT_MULTI_PAYMENT, NAV, PA_EMITTENTE, IUV, TOKEN, AMOUNT, FEE, ID_CARRELLO, STAZIONE, INTERMEDIARIO_PA, PSP, CANALE, INTERMEDIARIO_PSP, OUTCOME, TOUCHPOINT, PAYMENT_METHOD, SESSION_ID, UNIQUE_ID, TIPO_EVENTO, SOTTO_TIPO_EVENTO, SERVICE_IDENTIFIER
${estimates}

