spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}

  batch:
    job:
      enabled: ${SPRING_BATCH_JOB_ENABLED:false}

server:
  port: ${SERVER_PORT:8080}

azure:
  kusto:
    cluster:
      url: ${AZURE_KUSTO_CLUSTER_URL}
    app:
      id: ${AZURE_KUSTO_APP_ID}
      key: ${AZURE_KUSTO_APP_KEY}
    tenant:
      id: ${AZURE_KUSTO_TENANT_ID}

ingestion:
  database:
    schema: ${INGESTION_DATABASE_SCHEMA:sert_ingestor}
  first-run-start: 2026-03-23T00:00:00Z
  adx:
    endpoint: ${INGESTION_ADX_ENDPOINT:${AZURE_KUSTO_CLUSTER_URL}}
    database: ${INGESTION_ADX_DATABASE:${AZURE_KUSTO_DATABASE_NAME:re}}
    windows:
      EVENTS_WF: 5m
  quartz:
    jobs:
      ANAG_DESCRIPTION_REFRESH:
        cron: "0 0 0 * * ?"
        enabled: true
