spring.application.name=cruscotto-ingestor
spring.datasource.url=jdbc:postgresql://localhost:5432/pagopa
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=8080

# Liquibase Configuration
spring.liquibase.change-log=classpath:db/migration/liquibase/changelog/db.changelog-master.xml
spring.liquibase.enabled=true


# Azure Data Explorer (Kusto) Configuration
azure.kusto.cluster.url=https://<cluster-name>.<region>.kusto.windows.net
azure.kusto.app.id=<client-id>
azure.kusto.app.key=<client-secret>
azure.kusto.tenant.id=<tenant-id>
azure.kusto.database.name=<database-name>

# JPA Batch Insert/Update optimizations per grandi moli di dati
spring.jpa.properties.hibernate.jdbc.batch_size=2000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true


