# Azure Terraform Backend Storage Account configuration
# https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview
# Run this backend init once: terraform init -backend-config="env/dev/backend.tfvars"

# Azure subscription ID and name
subscription="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"  # dev subscription

# Terraform remote state storage
resource_group_name="io-infra-rg"
storage_account_name="pagopainfraterraformd"
container_name="tfstate"
key="cruscotto-ingestor-dev.tfstate"

