# Azure Terraform Backend Storage Account configuration for UAT
subscription="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"  # uat subscription

# Terraform remote state storage
resource_group_name="io-infra-rg"
storage_account_name="pagopainfraterraformu"
container_name="tfstate"
key="cruscotto-ingestor-uat.tfstate"

