apiVersion: v2
name: pagopacruscottoingestor
description: PagoPA Cruscotto Ingestor Helm chart
type: application
version: 0.8.0
appVersion: 0.3.1
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
