# Azure Terraform Backend Storage Account configuration for PROD
subscription="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"  # prod subscription

# Terraform remote state storage
resource_group_name="io-infra-rg"
storage_account_name="pagopainfraterraformp"
container_name="tfstate"
key="cruscotto-ingestor-prod.tfstate"

