name: Release And Deploy

on:
  merge_group:
    branches: [main]
  pull_request:
    types: [closed]

  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the Environment
        options:
          - dev
          - uat
          - prod
      version:
        required: false
        type: choice
        description: Select the version
        options:
          - patch
          - skip_or_promote
          - minor
          - major
          - skip

permissions:
  packages: write
  contents: write
  issues: write
  id-token: write
  actions: read

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.get_semver.outputs.semver }}
      environment: ${{ steps.get_env.outputs.environment }}
    steps:
      - name: pull request rejected
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged != true
        run: |
          echo "❌ PR was closed without a merge"
          exit 1

      - run: echo "SEMVER=patch" >> $GITHUB_ENV

      - if: ${{ (github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'skip')) }}
        run: echo "SEMVER=skip" >> $GITHUB_ENV

      - if: ${{ (github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'patch')) }}
        run: echo "SEMVER=patch" >> $GITHUB_ENV

      - if: ${{ (github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'minor')) }}
        run: echo "SEMVER=minor" >> $GITHUB_ENV

      - if: ${{ (github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'major')) }}
        run: echo "SEMVER=major" >> $GITHUB_ENV

      - if: ${{ inputs.version == 'minor' }}
        run: echo "SEMVER=minor" >> $GITHUB_ENV

      - if: ${{ inputs.version == 'major' }}
        run: echo "SEMVER=major" >> $GITHUB_ENV

      - if: ${{ github.ref_name != 'main' }}
        run: echo "SEMVER=buildNumber" >> $GITHUB_ENV

      - if: ${{ inputs.version == 'skip_or_promote' }}
        run: echo "SEMVER=skip" >> $GITHUB_ENV

      - id: get_semver
        name: Set Output
        run: echo "semver=${{env.SEMVER}}" >> $GITHUB_OUTPUT

      - run: echo "ENVIRNOMENT=${{ inputs.environment}}" >> $GITHUB_ENV

      - if: ${{ inputs.environment == null }}
        run: echo "ENVIRNOMENT=dev" >> $GITHUB_ENV

      - id: get_env
        name: Set Output
        run: echo "environment=${{env.ENVIRNOMENT}}" >> $GITHUB_OUTPUT

  release:
    name: Create a New Release
    runs-on: ubuntu-latest
    needs: [setup]
    if: ${{ needs.setup.outputs.semver != 'skip' }}
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: Make Release
        id: release
        uses: pagopa/github-actions-template/maven-release@4a4c25ce28feeec9e619b3132b5327f52023d441
        with:
          semver: ${{ needs.setup.outputs.semver }}
          github_token: ${{ secrets.BOT_TOKEN_GITHUB }}
          prerelease: ${{  github.ref_name != 'main' }}
          only_tag: false

  preflight:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Enforce prod deploy from main only
        if: ${{ needs.setup.outputs.environment == 'prod' && github.ref_name != 'main' }}
        run: |
          echo "Prod deploy is allowed only from main branch. Current branch: ${{ github.ref_name }}"
          exit 1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Helm lint
        run: |
          helm dependency update helm
          helm lint helm -f "helm/values-${{ needs.setup.outputs.environment }}.yaml"
    needs: [setup]

  image:
    needs: [setup, preflight]
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    if: ${{ needs.setup.outputs.semver != 'skip' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Build and Push
        id: semver
        uses: pagopa/github-actions-template/ghcr-build-push@d91a1fd0b913c9830589be5d86cdb71c90813fae # v1.5.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.release.outputs.version }}
          build_args: APP_NAME=cruscotto-ingestor

  deploy:
    needs: [setup, release, image]
    if: ${{ always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
    runs-on: [self-hosted-job, '${{ needs.setup.outputs.environment }}']
    environment: ${{ needs.setup.outputs.environment }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Deploy
        uses: pagopa/github-actions-template/aks-deploy@main
        with:
          branch: ${{ github.ref_name }}
          client_id: ${{ secrets.CD_CLIENT_ID }}
          subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.TENANT_ID }}
          env: ${{ needs.setup.outputs.environment }}
          namespace: ${{ vars.NAMESPACE }}
          cluster_name: ${{ vars.CLUSTER_NAME }}
          resource_group: ${{ vars.CLUSTER_RESOURCE_GROUP }}
          app_name: cruscotto-ingestor
          helm_upgrade_options: '--debug --set microservice-chart.azure.workloadIdentityClientId=${{vars.WORKLOAD_IDENTITY_ID}} --set microservice-chart.image.tag=${{ needs.release.outputs.version }}'
          timeout: '10m0s'


